title:            "@crabcanon/黄野"
url:              http://yehuang.me
permalink:        pretty
highlighter:      pygments
google_analytics: UA-45466555-1
timezone:         Europe/Helsinki
exclude_from_search: true
lunr_search:
  min_length: 5
  js_dir: "assets/js"
  excludes: [feed.xml]
sass:
  sass_dir: assets
  style: :compressed
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-lunr-js-search
  - jekyll-sitemap
