title: "黄野 | @crabcanon"
url: https://yehuang.me
permalink: pretty
highlighter: rouge
google_analytics: UA-45466555-1
timezone: Europe/Helsinki
exclude_from_search: true
lunr_search:
  min_length: 5
  js_dir: "assets/js"
  excludes: [feed.xml]
sass:
  sass_dir: assets
  style: :compressed
offline:
  strategy: cache-then-network
gems:
  - jemoji
  - jekyll-mentions
  - jekyll-lunr-js-search
  - jekyll-sitemap
